name: Java Publish Test
on: push

jobs:
  build_artifact:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/jsii-terraform
    env:
      CHECKPOINT_DISABLE: "1"

    steps:
      - uses: actions/checkout@v2
      - name: installing dependencies
        run: |
          yarn install
      - name: compile
        run: |
          tools/align-version.sh "-pre.${{ github.run_number }}"
          yarn build
      - name: create bundle
        run: yarn package
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist

  publish_java:
    runs-on: ubuntu-latest
    needs: build_artifact
    if: false
    steps:
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/checkout@v2
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Publish package
        run: yarn release-github-maven
        env:
          MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_SERVER_ID: github
          MAVEN_REPOSITORY_URL: "https://maven.pkg.github.com/${{ github.repository }}"

  release_maven_github:
    name: Release to GitHub Maven
    needs: build_artifact
    runs-on: ubuntu-latest
    container:
      image: hashicorp/jsii-terraform
    steps:
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Release
        run: npx -p jsii-release jsii-release-maven
        env:
          MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_SERVER_ID: github
          MAVEN_REPOSITORY_URL: "https://maven.pkg.github.com/${{ github.repository }}"